### ISSUE TITLE
 Could not find Custom Field: plugin::ckeditor5video.CKEditor5Video

### ISSUE THREAD

**Issue by vinubabu323** [hrahimi270/strapi-plugin-ckeditor-video#1] opened 2024-01-19 04:31 UTC
![plugin-error](https://github.com/hrahimi270/strapi-plugin-ckeditor-video/assets/72564243/fbc3633a-f764-4da4-b333-c843602d5ce6)

This error is showing in application.

**Comment by vinubabu323** [comment] 2024-01-19 06:02
Strapi version : 4.10.4 (node v16.16.0)

**Comment by m7jxc** [comment] 2024-01-25 05:08
same error. any solutions?

**Comment by mplutka** [comment] 2024-04-12 14:42
Inside server/register.js
name needs to be 'CKEditor5Video'

**Comment by hrahimi270** [comment] 2024-05-20 09:57
@vinubabu323 @m7jxc @mplutka  Sorry for so late respond. The problem is fixed on version 0.0.5.

**Closed as completed by hrahimi270** 2024-05-20 09:57 UTC
